---
title: "Patient Flow Metrics Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
fls=list.files(path='~/edtf_prototype/r_scripts',pattern='.R',full.names=T)
for(i in fls){source(i)}
rm(i,fls)
code=9999
```

Front-End Inflow
=======================================

Row {data-height=200}
-----------------------------------------------------------------------

### ED Activity

```{r}
edtf_ed_activity(code)
```

### Monthly PET
```{r,fig.height=1}
edtf_monthly_pet(code)
```

### Trolleys (8am)
```{r,fig.height=1}
edtf_trolleys_8am(code)
```

Row
-------------------------------------
### Hourly ED Attendances
```{r}
edtf_hourly_ed_attendances2(code)
```

### Daily ED Attendances
```{r}
edtf_daily_ed_attendances2(code)
```

Row
---------------------------------------
### Trolley 8am 30 Day Moving Average
```{r}
edtf_trolleys_8am_30_dma(code)
```

Throughput
===============================

Row {data-height=200}
-----------------------------------------------------------------------

### Admissions YTD

```{r}
edtf_admissions_ytd(code)
```

### AvLOS (Medical)
```{r}
edtf_avlos_medical(code)
```

### AvLOS by Specialty - Top 3 BDL
```{r}
edtf_avlos_by_specialty(code)
```

Row
----------------------------------
### HIPE Admissions by Hour

```{r}
edtf_hipe_admissions_by_hour(code)
```

### HIPE Admissions by Day
```{r}
edtf_hipe_admissions_by_day(code)
```

Egress
=================================

Row {data-height=150}
--------------------------------

### Discharges
```{r,fig.height=1}
edtf_discharges(code)
```

Row
-----------------------
### HIPE Discharges by Hour
```{r}
edtf_hipe_discharges_by_hour(code)
```

### HIPE Discharges by Day
```{r}
edtf_hipe_discharges_by_day(code)
```

Row
-----------------------------------
### Delayed Discharges by Destination
```{r}
edtf_delayed_discharges_by_destination(code)
```
